name: Full Pipeline
kind: pipeline
type: docker

environment:
  SONAR_KEY_dev: "mycelium-local-dev"
  SONAR_KEY_uat: "mycelium-local-uat"
  SONAR_KEY_master: "mycelium-local-master"
  SONAR_NAME_dev: "Mycelium Local Dev"
  SONAR_NAME_uat: "Mycelium Local UAT"
  SONAR_NAME_master: "Mycelium Local Master"

steps:
  - name: Unit testing
    image: gradle:7.5.1-jdk17
    commands:
      - cd api
      - gradle test

trigger:
  branch:
    - dev
    - uat
    - master
