name: mycelium-local-dev

services:
  nginx-proxy:
    image: nginx
    ports:
      - "6062:80/tcp"
    volumes:
      - ./default.conf:/etc/nginx/templates/default.conf.template:z,ro
    networks:
      mycelium-local:
      mycelium-global:
        aliases:
          - mycelium-local
    depends_on:
      - api
      - client

  api:
    image: localhost/mycelium-local_api:dev
    expose:
      - "8080"
    volumes:
      - ./api:/app:z,rw
      - gradle:/var/lib/gradle:z,rw
    build:
      context: api
      dockerfile: Dockerfile.dev
    networks:
      - mycelium-local
      - mycelium-global
    depends_on:
      - db

  client:
    image: localhost/mycelium-local_client:dev
    expose:
      - "3000"
    volumes:
      - ./client:/app:z,rw
    build:
      context: client
      dockerfile: Dockerfile.dev
    networks:
      - mycelium-local
      - mycelium-global

  db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - 2521:1521
    restart: unless-stopped
    environment:
      ORACLE_PWD: "12345"
    volumes:
      - oracledb:/opt/oracle/oradata:z,rw
    networks:
      mycelium-local:
        aliases:
          - myceliumdb

volumes:
  oracledb:
  gradle:

networks:
  mycelium-local:
    driver: bridge
  mycelium-global:
    external: true
