name: mycelium-local-dev-devops

services:
  sonarqube-server:
    image: docker.io/sonarqube:10.1.0-community
    ports:
      - 9000:9000
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    depends_on:
      - sonarqube-db

  sonarqube-db:
    image: docker.io/postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - sonarqube_db_data:/var/lib/postgresql/data:z,rw

  jenkins:
    image: docker.io/jenkins/jenkins:2.401.3-lts-jdk17
    ports:
      - 8080:8080
    volumes:
      - ${DOCKER_SOCKET_PATH:-/var/run/docker.sock}:/var/run/docker.sock
      - jenkins_data:/var/jenkins_home:z,rw
    env_file:
      - .env
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

volumes:
  sonarqube_db_data:
  jenkins_data:
